### ISSUE TITLE
What does OSS mean?

### ISSUE THREAD

**Issue by felipewind** [bancodobrasil/poppins#11]
Hello!
In the README.md is written 

> A project is considerate a "Poppins project" if it is mainly managed to help beginners to level up their skills and increase their experience with OSS in a mentorship community atmosphere.

I'm a begginer, and I'd like to confirm the meaning of **OSS**.

Does **OSS** mean **Open Source Software** ?

Thanks a lot.

**Comment by tiagostutz** [comment]
Hi there @felipewind .!! That’s so nice to have you here.

Yep, you got it right. OSS = Open Source Software ✅

**Comment by felipewind** [comment]
Thanks a lot @tiagostutz !
