### ISSUE TITLE
README.md review

### ISSUE THREAD

**Issue by TCashion** [bancodobrasil/poppins#12]
@tiagostutz as you suggested, I can make some documentation improvements for you here.

**Comment by tiagostutz** [comment]
Thanks @TCashion .!

I renamed the issue to target specifically the README docs. I’ll open another issue for the contributing docs and offer it to some new contributor linking your PR and asking your supervision and support on the PR. 

Sounds good to you?

**Comment by TCashion** [comment]
@tiagostutz sounds great!!
